import type { BatterCard, PitcherCard } from "../domain/cards.ts";
import type { Coord, Column, Row } from "../domain/field.ts";
import { COLUMNS } from "../domain/field.ts";
import type { Player, Strength, Handedness, TeamSide } from "../domain/players.ts";
import type { Bases } from "../engine/runners.ts";
import { runnersOnBase } from "../engine/runners.ts";
import type { Rng } from "../engine/rng.ts";

export type AiPublicState = {
  inning: number;
  inningsConfigured: number;
  half: "Top" | "Bottom";
  outs: number;
  bases: Bases;
  myScore: number;
  opponentScore: number;
};

export type Ai = {
  /** Choose a batter card from the AI's own hand. */
  chooseBatterCard(hand: readonly BatterCard[], state: AiPublicState, batter: Player): BatterCard;
  /** Choose a pitcher card from the AI's own hand. */
  choosePitcherCard(hand: readonly PitcherCard[], state: AiPublicState, opposingBatter: Player): PitcherCard;
  /**
   * Place 8 fielders to defend against the given batter. Returns 8 unique
   * coordinates (the engine adds the pitcher automatically).
   */
  placeFielders(batter: Player): Coord[];
};

const uniformWeights = (n: number) => Array.from({ length: n }, () => 1);

export function createAi(rng: Rng, mySide: TeamSide): Ai {
  void mySide; // reserved for future side-aware heuristics

  const chooseBatterCard = (
    hand: readonly BatterCard[],
    state: AiPublicState,
    _batter: Player,
  ): BatterCard => {
    if (hand.length === 0) throw new Error("AI has no batter cards");
    const runners = runnersOnBase(state.bases);
    const lateGame = state.inning >= state.inningsConfigured;
    const trailing = state.myScore < state.opponentScore;

    // Build weights matching hand cards.
    const weights = hand.map((card) => weightForBatter(card, hand, runners, state, lateGame, trailing));
    return rng.weighted(hand, weights);
  };

  const choosePitcherCard = (
    hand: readonly PitcherCard[],
    state: AiPublicState,
    _opposingBatter: Player,
  ): PitcherCard => {
    if (hand.length === 0) throw new Error("AI has no pitcher cards");
    const weights = hand.map((card) => weightForPitcher(card, hand, state));
    return rng.weighted(hand, weights);
  };

  const placeFielders = (batter: Player): Coord[] => {
    return defaultFielderPlacement(batter.strength, batter.handedness);
  };

  return { chooseBatterCard, choosePitcherCard, placeFielders };
}

function weightForBatter(
  card: BatterCard,
  hand: readonly BatterCard[],
  runners: Player[],
  state: AiPublicState,
  lateGame: boolean,
  trailing: boolean,
): number {
  const has = (c: BatterCard) => hand.includes(c);
  let w = 1;
  switch (card) {
    case "HighSwing":
    case "LowSwing":
    case "FlatSwing":
      w = 3; // bread and butter
      break;
    case "HitAndRun":
      w = runners.length > 0 && state.outs < 2 ? 4 : 1;
      break;
    case "Walk":
      // Useful late, conservative when ahead.
      w = lateGame && !trailing ? 2 : 1;
      break;
    case "StolenBase":
      // Best with runner on 1B and 2B empty.
      if (state.bases.first && !state.bases.second && state.outs < 2) w = 3;
      else if (runners.length === 0) w = 0; // do not waste on empty bases
      else w = 1;
      break;
    case "Sacrifice":
      // Useful with runner on 2B/3B and <2 outs and tied/trailing.
      if ((state.bases.second || state.bases.third) && state.outs < 2 && trailing) w = 3;
      else w = 0.5;
      break;
    case "Box":
      // Most useful when opponent likely has many NoPitch cards left;
      // we don't track opponent hand precisely. Use modest weight.
      w = has("Box") ? 1 : 0;
      break;
  }
  return w;
}

function weightForPitcher(
  card: PitcherCard,
  hand: readonly PitcherCard[],
  state: AiPublicState,
): number {
  const noPitchCount = hand.filter((c) => c === "NoPitch").length;
  switch (card) {
    case "NoPitch":
      // Burn judiciously — fewer in pivotal situations (runners on base).
      if (state.bases.third && state.outs < 2) return 0.5;
      return Math.max(0.5, noPitchCount); // weight scales with how many we have
    default:
      return 2;
  }
}

/**
 * Default 8-fielder placement (auto-generated by the AI or used as a sane
 * starter for the human UI). Adjusts depth and pull-side bias by batter
 * Strength and Handedness. Returns exactly 8 coordinates.
 */
export function defaultFielderPlacement(
  strength: Strength,
  handedness: Handedness,
): Coord[] {
  // Outfield depth row depends on strength.
  const outfieldRow: Row =
    strength === "Light" ? 7 : strength === "Medium" ? 8 : 10;
  // Pull-side shift: RHB pulls to A side, LHB pulls to O side.
  const shift = handedness === "Right" ? -1 : 1;

  const cols = (i: number): Column => {
    const idx = Math.max(0, Math.min(COLUMNS.length - 1, i + shift));
    return COLUMNS[idx] as Column;
  };

  // Infield: 4 players covering the diamond approximately at row 4.
  const infieldRow: Row = 4;
  const infield: Coord[] = [
    { col: cols(2), row: infieldRow }, // 3B-ish
    { col: cols(6), row: infieldRow }, // SS / 2B
    { col: cols(8), row: infieldRow }, // 2B
    { col: cols(12), row: infieldRow }, // 1B-ish
  ];

  // Outfield: 3 players (LF, CF, RF) at outfield depth.
  const outfield: Coord[] = [
    { col: cols(2), row: outfieldRow }, // LF
    { col: cols(7), row: outfieldRow }, // CF
    { col: cols(12), row: outfieldRow }, // RF
  ];

  // Catcher / utility: place near home to cover error square area.
  const catcherLike: Coord = { col: "B", row: 4 };

  // Combine and ensure exactly 8.
  const all: Coord[] = [...infield, ...outfield, catcherLike];
  // Dedupe by string key in case of overlap.
  const seen = new Set<string>();
  const unique: Coord[] = [];
  for (const c of all) {
    const k = `${c.col}${c.row}`;
    if (!seen.has(k)) {
      seen.add(k);
      unique.push(c);
    }
  }
  // If we lost any to dedupe, pad with extra outfielders at distinct columns.
  let pad = 0;
  while (unique.length < 8) {
    const candidate: Coord = { col: COLUMNS[(7 + pad) % COLUMNS.length] as Column, row: 9 };
    const k = `${candidate.col}${candidate.row}`;
    if (!seen.has(k)) {
      seen.add(k);
      unique.push(candidate);
    }
    pad++;
    if (pad > 30) break;
  }
  return unique.slice(0, 8);
}

// Make uniformWeights available for tests / future tuning.
export const _uniformWeights = uniformWeights;
